### PR TITLE
Fix tests warning about imghdr being deprecated

### PR DESCRIPTION
**Pull request by orontee**
Part of #21

### CODE REVIEW

**Comment by jodal** [comment]
Thanks!

**Comment by jfhbrook** [comment]
Did this get released? [Python 3.13 fully removed imghdr](https://docs.python.org/3/library/imghdr.html), meaning mopidy-local 3.2.1 won't install on many Linux OS's (such as Fedora 40).

**Comment by jodal** [comment]
No, it did not. I'll see about getting a bugfix release out one of the next days.

**Comment by jfhbrook** [comment]
Excellent! Thank you, I appreciate it.

**Comment by jodal** [comment]
I released v3.3.0 now with all the fixes that landed before I started working on project modernization last month. Let me know if anything doesn't work on Python 3.13!

**Comment by jfhbrook** [comment]
My Fedora 41 package is building, which means it's importing correctly! I'll file another issue if I run into something going forward. Cheers! 🤝

**Pull request merged**
