### PR TITLE
Add back use_artist_mbid_uri and use_album_mbid_uri

### LINKED ISSUE #26: Put back the use_album_mbid_uri option that was in local-sqlite
Using MBIDs to create uris can have unintended consequences. With local-sqlite I could switch this off but this option seems to have been removed in the new mopidy-local.

As an example, I have 2 albums that I tagged with Musicbrainz Picard.

One has 'Artist = Brian Eno'
One has 'Artist = Brian Eno & Jah Wobble'

They're also tagged with musicbrainz IDs for the artists. The second album has two artist ID tags even though it only has one artist. (This is the way Musicbrainz reccomend it is done). Since the scanner can only use one mbid to create the artist URI, both albums end up under 'Brian Eno and Jah Wobble'.

With the old local-sqlite setting use_album_mbid_uri = false in mopidy.conf fixed this.

### PR DESCRIPTION
**Pull request by fatg3erman**
At least on my collection of files, about 10% of them don't sort correctly when using MBIDs to create URIs. I tag all my files using Picard, so I can't be the only person who'll encounter this.

Fixes #26

### CODE REVIEW

**Comment by kingosticks** [comment]
Running `tox` locally is worth doing before committing/pushing, this includes `black .`.

**Comment by fatg3erman** [comment]
Yeah, I'm having difficulty getting the full development virtualenv to work on macOS. I had it working with python 2.7 but even then only for mopidy core, I could never get it to find extensions. Currently it's totally broken and I don't understand why.

**Comment by kingosticks** [comment]
Ah OK well I can't help at all with that. You could try posting in discourse to see if anyone else has a working mac dev environment. Or @jodal may have some tips.

**Comment by tkem** [comment]
@fatg3erman: as discussed in #26, getting rid of the `mbid` URI scheme altogether for now would probably be a better option than re-introducing those configuration options. Could you be bothered to create another PR for that - should be much easier, effectively removing just a few lines? Or shall I close this and give it a try myself?

**Comment by fatg3erman** [comment]
@tkem yes I can do that, need to find the time to get round to it but as you say it won't be hard.

**Comment by fatg3erman** [comment]
Closing - will create a new one (on a new branch) to remove these options.

**Pull request closed without merging**
