### PR TITLE
Remove code for creating URIs from Musicbrainz IDs

### LINKED ISSUE #26: Put back the use_album_mbid_uri option that was in local-sqlite
Using MBIDs to create uris can have unintended consequences. With local-sqlite I could switch this off but this option seems to have been removed in the new mopidy-local.

As an example, I have 2 albums that I tagged with Musicbrainz Picard.

One has 'Artist = Brian Eno'
One has 'Artist = Brian Eno & Jah Wobble'

They're also tagged with musicbrainz IDs for the artists. The second album has two artist ID tags even though it only has one artist. (This is the way Musicbrainz reccomend it is done). Since the scanner can only use one mbid to create the artist URI, both albums end up under 'Brian Eno and Jah Wobble'.

With the old local-sqlite setting use_album_mbid_uri = false in mopidy.conf fixed this.

### PR DESCRIPTION
**Pull request by fatg3erman**
Remove any code that was used for creating URIs from MBIDs.

Fixes #26

### CODE REVIEW

**Comment by fatg3erman** [comment]
I don't even know what this failure means.

Honestly, I was considering suggesting myself as maintainer for this, but these checks are unintelligible and *ridiculously* pedantic.

**Comment by kingosticks** [comment]
What failure are you talking about?

**Comment by kingosticks** [comment]
If you are talking about the codecov failure, then it's basically telling you that you didn't test anything that you changed.  The tests for this extension are not brilliant anyway, and it's not going to stop anyone merging this.

**Comment by jodal** [comment]
The "codecov/project" test tells us that the project as a whole's test coverage is 51.4%, and merging this PR will increase the test coverage with +0.27%.

The "codecov/patch" test, which is the one failing, tells us that the code changed by this PR has 0% test coverage, which is less than the goal of 51.12%, which is the project's test coverage before this PR is merged. In other words, the code changed by the PR has less coverage than the project as a whole. Assuming this PR was adding code, not removing it, that would cause the project as a whole to get less test coverage, which is moving in the right direction.

I tend to view these reports as "extra information" and not something blocking me from merging. I've seen it positively affect new contributors by nudging them to make the extra effort to test their changes better. If we all did that, we'd end up in a great place over time.

**Comment by fatg3erman** [comment]
As a professional QA engineer for 25 years I'd be the first to agree that nobody does enough testing :)

As for 'ridiculously pedantic' I was more referring to flake8. While I agree with the need for code to be elegant and readable I feel it stretches into nitpicking territory and it annoys the lviing **** out of me. It puts me off contributing more than it helps. But that's just me.

If I get the time I'll update the changelog and commit it.

**Pull request merged**
